import localFont from "next/font/local";
import "./globals.css";
import Topbar from "./components/Topbar";
import Navbar from "./navigation/Navbar";
import Footer from "./navigation/Footer";
import CustomIcons from "./components/CustomIcons";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<CustomIcons>
				<body
					className={`${geistSans.variable} ${geistMono.variable} antialiased text-sm relative`}
				>
					<Topbar className={geistMono.variable} />
					<Navbar />
					{children}
					<Footer />
				</body>
			</CustomIcons>
		</html>
	);
}
